version: '2'
services:
  redis:
    image: redis

  elasticsearch:
    image: elasticsearch

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: homestead
      POSTGRES_DB: forevr
      PGDATA: /var/lib/postgresql/data
    volumes:
      - $PWD/db:/var/lib/postgresql/data:Z

  web:
    build: ./php
    ports: 
      - "80:80"
    volumes:
      - /home/sukach/work/forevr/project/BE:/opt/app/current:Z
    links:
      - redis
      - elasticsearch
    depends_on:
      - db
      - redis
      - elasticsearch
